import {
  RECEIPT_CAMERA_ACCEPT_TYPES,
  RECEIPT_FILE_ACCEPT_TYPES,
  RECEIPT_MAX_FILE_BYTES,
} from '@/features/receipt-scans/lib/receiptUploadGuards';

export const SCROLL_BOTTOM_THRESHOLD_PX = 120;
export const OVERLAY_DISMISS_DRAG_PX = 82;
export { RECEIPT_CAMERA_ACCEPT_TYPES, RECEIPT_FILE_ACCEPT_TYPES, RECEIPT_MAX_FILE_BYTES };
