import { Router } from 'express';
import authRoutes from '../modules/auth/routes';
import accountRoutes from '../modules/accounts/routes';
import categoryRoutes from '../modules/categories/routes';
import sectionRoutes from '../modules/sections/routes';
import transactionRoutes from '../modules/transactions/routes';
import referralRoutes from '../modules/referral/routes';
import notificationRoutes from '../modules/notifications/routes';
import recurringRoutes from '../modules/recurring/routes';
import userRoutes from '../modules/users/routes';
import aiRoutes from '../modules/ai/routes';
import progressionRoutes from '../modules/progression/routes';
import aiSettingsRoutes from '../modules/ai-settings/routes';
import companionRoutes from '../modules/companion/routes';
import subscriptionRoutes from '../modules/subscription/routes';
import goalRoutes from '../modules/goals/routes';
import adminRoutes from '../modules/admin/routes';
import analyticsRoutes from '../modules/analytics/routes';
import obligationRoutes from '../modules/obligations/routes';
import reportRoutes from '../modules/reports/routes';
import spendingLimitRoutes from '../modules/spending-limits/routes';
import paymentsRoutes from '../modules/payments/routes';
import receiptScanRoutes from '../modules/receipt-scans/routes';
import telegramBotRoutes from '../modules/telegram-bot/routes';
import financialCycleRoutes from '../modules/financial-cycle/routes';
const router = Router();

router.use('/auth', authRoutes);
router.use('/accounts', accountRoutes);
router.use('/categories', categoryRoutes);
router.use('/sections', sectionRoutes);
router.use('/transactions', transactionRoutes);
router.use('/referral', referralRoutes);
router.use('/notifications', notificationRoutes);
router.use('/recurring', recurringRoutes);
router.use('/users', userRoutes);
router.use('/ai', aiRoutes);
router.use('/progression', progressionRoutes);
router.use('/ai-settings', aiSettingsRoutes);
router.use('/companion', companionRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/goals', goalRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/obligations', obligationRoutes);
router.use('/reports', reportRoutes);
router.use('/spending-limits', spendingLimitRoutes);
router.use('/payments', paymentsRoutes);
router.use('/receipt-scans', receiptScanRoutes);
router.use('/telegram-bot', telegramBotRoutes);
router.use('/financial-cycle', financialCycleRoutes);
router.use('/admin', adminRoutes);
export default router;