import type { TaxonomyIconRule } from '../types';

export const leisureTravelRules: TaxonomyIconRule[] = [
  {
    "id": "cinema",
    "type": "expense",
    "sectionId": "entertainment",
    "sectionName": "Развлечения",
    "sectionIcon": "🎮",
    "sectionColor": "#22D3EE",
    "categoryName": "Кино и события",
    "categoryIcon": "🎟️",
    "categoryColor": "#22D3EE",
    "keywords": [
      "кино",
      "театр",
      "концерт",
      "билет",
      "мероприятие",
      "выставка",
      "музей",
      "стендап",
      "цирк",
      "фестиваль"
    ]
  },
  {
    "id": "games",
    "type": "expense",
    "sectionId": "entertainment",
    "sectionName": "Развлечения",
    "sectionIcon": "🎮",
    "sectionColor": "#22D3EE",
    "categoryName": "Игры",
    "categoryIcon": "🎮",
    "categoryColor": "#22D3EE",
    "keywords": [
      "игра",
      "игры",
      "steam",
      "стим",
      "playstation",
      "ps store",
      "xbox",
      "донат",
      "внутриигровая покупка",
      "roblox",
      "steam purchase",
      "epic games",
      "genshin",
      "pubg",
      "dota",
      "cs go",
      "minecraft",
      "fortnite",
      "донат игра"
    ]
  },
  {
    "id": "books",
    "type": "expense",
    "sectionId": "education",
    "sectionName": "Образование",
    "sectionIcon": "🎓",
    "sectionColor": "#4ADE80",
    "categoryName": "Книги",
    "categoryIcon": "📚",
    "categoryColor": "#4ADE80",
    "keywords": [
      "книга",
      "книги",
      "литрес",
      "учебник",
      "журнал",
      "комикс",
      "аудиокнига"
    ]
  },
  {
    "id": "courses",
    "type": "expense",
    "sectionId": "education",
    "sectionName": "Образование",
    "sectionIcon": "🎓",
    "sectionColor": "#4ADE80",
    "categoryName": "Курсы",
    "categoryIcon": "🎓",
    "categoryColor": "#4ADE80",
    "keywords": [
      "курс",
      "курсы",
      "обучение",
      "школа",
      "университет",
      "вебинар",
      "урок",
      "репетитор",
      "английский",
      "образование",
      "skyeng",
      "skillbox",
      "нетология",
      "coursera",
      "udemy",
      "stepik",
      "geekbrains",
      "репетитор математика",
      "урок английского"
    ]
  },
  {
    "id": "flights",
    "type": "expense",
    "sectionId": "travel",
    "sectionName": "Путешествия",
    "sectionIcon": "✈️",
    "sectionColor": "#2DD4BF",
    "categoryName": "Авиабилеты",
    "categoryIcon": "✈️",
    "categoryColor": "#2DD4BF",
    "keywords": [
      "самолет",
      "авиабилет",
      "авиа",
      "перелет",
      "аэропорт",
      "s7",
      "аэрофлот",
      "победа",
      "utair"
    ]
  },
  {
    "id": "hotel",
    "type": "expense",
    "sectionId": "travel",
    "sectionName": "Путешествия",
    "sectionIcon": "✈️",
    "sectionColor": "#2DD4BF",
    "categoryName": "Отели",
    "categoryIcon": "🏨",
    "categoryColor": "#2DD4BF",
    "keywords": [
      "отель",
      "гостиница",
      "хостел",
      "airbnb",
      "апартаменты",
      "бронь жилья",
      "проживание"
    ]
  },
  {
    "id": "vacation",
    "type": "expense",
    "sectionId": "travel",
    "sectionName": "Путешествия",
    "sectionIcon": "✈️",
    "sectionColor": "#2DD4BF",
    "categoryName": "Отпуск",
    "categoryIcon": "🏖️",
    "categoryColor": "#2DD4BF",
    "keywords": [
      "отпуск",
      "тур",
      "путевка",
      "курорт",
      "пляж",
      "экскурсия",
      "путешествие",
      "поездка"
    ]
  },
  {
    "id": "visa",
    "type": "expense",
    "sectionId": "travel",
    "sectionName": "Путешествия",
    "sectionIcon": "✈️",
    "sectionColor": "#2DD4BF",
    "categoryName": "Визы и документы",
    "categoryIcon": "🛂",
    "categoryColor": "#2DD4BF",
    "keywords": [
      "виза",
      "загранпаспорт",
      "паспорт",
      "страховка туриста",
      "документы поездка"
    ]
  },
  {
    "id": "loan",
    "type": "expense",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Кредиты",
    "categoryIcon": "💳",
    "categoryColor": "#FCD34D",
    "keywords": [
      "кредит",
      "займ",
      "платеж по кредиту",
      "рассрочка",
      "долг",
      "микрозайм",
      "погашение кредита"
    ]
  },
  {
    "id": "bank_fee",
    "type": "expense",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Банковские комиссии",
    "categoryIcon": "🏦",
    "categoryColor": "#FCD34D",
    "keywords": [
      "комиссия",
      "банковская комиссия",
      "обслуживание карты",
      "смс банк",
      "плата банка"
    ]
  },
  {
    "id": "tax",
    "type": "expense",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Налоги",
    "categoryIcon": "🧾",
    "categoryColor": "#FCD34D",
    "keywords": [
      "налог",
      "налоги",
      "фнс",
      "патент",
      "самозанятый налог",
      "усн",
      "страховые взносы"
    ]
  }
];
