import type { TaxonomyIconRule } from '../types';

export const lifestyleRules: TaxonomyIconRule[] = [
  {
    "id": "pharmacy",
    "type": "expense",
    "sectionId": "health",
    "sectionName": "Здоровье",
    "sectionIcon": "🩺",
    "sectionColor": "#F87171",
    "categoryName": "Аптека",
    "categoryIcon": "💊",
    "categoryColor": "#F87171",
    "keywords": [
      "аптека",
      "лекарства",
      "таблетки",
      "витамины",
      "мазь",
      "капли",
      "антибиотик",
      "обезболивающее",
      "фармация",
      "36.6",
      "ригла",
      "аптека ру",
      "аптечный",
      "здравсити",
      "парацетамол",
      "ибупрофен",
      "нурофен",
      "аспирин",
      "ингавирин",
      "омега"
    ]
  },
  {
    "id": "doctor",
    "type": "expense",
    "sectionId": "health",
    "sectionName": "Здоровье",
    "sectionIcon": "🩺",
    "sectionColor": "#F87171",
    "categoryName": "Врач",
    "categoryIcon": "🩺",
    "categoryColor": "#F87171",
    "keywords": [
      "врач",
      "доктор",
      "клиника",
      "анализы",
      "прием врача",
      "стоматолог",
      "зубы",
      "терапевт",
      "узи",
      "мрт",
      "медицина",
      "инвитро",
      "гемотест",
      "смд",
      "cmd",
      "поликлиника",
      "медцентр",
      "медси",
      "стоматология",
      "ортодонт",
      "пломба",
      "чистка зубов"
    ]
  },
  {
    "id": "fitness",
    "type": "expense",
    "sectionId": "sports",
    "sectionName": "Спорт",
    "sectionIcon": "🏋️",
    "sectionColor": "#34D399",
    "categoryName": "Фитнес",
    "categoryIcon": "🏋️",
    "categoryColor": "#34D399",
    "keywords": [
      "фитнес",
      "спортзал",
      "тренажерный зал",
      "абонемент",
      "тренер",
      "йога",
      "пилатес",
      "бассейн",
      "секция",
      "спорт"
    ]
  },
  {
    "id": "haircut",
    "type": "expense",
    "sectionId": "beauty",
    "sectionName": "Красота",
    "sectionIcon": "💅",
    "sectionColor": "#F472B6",
    "categoryName": "Парикмахер",
    "categoryIcon": "💇",
    "categoryColor": "#F472B6",
    "keywords": [
      "стрижка",
      "барбер",
      "парикмахер",
      "салон",
      "волосы",
      "окрашивание",
      "укладка"
    ]
  },
  {
    "id": "cosmetics",
    "type": "expense",
    "sectionId": "beauty",
    "sectionName": "Красота",
    "sectionIcon": "💅",
    "sectionColor": "#F472B6",
    "categoryName": "Косметика",
    "categoryIcon": "💄",
    "categoryColor": "#F472B6",
    "keywords": [
      "косметика",
      "крем",
      "помада",
      "тушь",
      "духи",
      "парфюм",
      "уход",
      "шампунь",
      "гель",
      "мейкап"
    ]
  },
  {
    "id": "manicure",
    "type": "expense",
    "sectionId": "beauty",
    "sectionName": "Красота",
    "sectionIcon": "💅",
    "sectionColor": "#F472B6",
    "categoryName": "Маникюр",
    "categoryIcon": "💅",
    "categoryColor": "#F472B6",
    "keywords": [
      "маникюр",
      "педикюр",
      "ногти",
      "шеллак",
      "лак"
    ]
  },
  {
    "id": "clothes",
    "type": "expense",
    "sectionId": "clothes",
    "sectionName": "Одежда",
    "sectionIcon": "👕",
    "sectionColor": "#C084FC",
    "categoryName": "Одежда",
    "categoryIcon": "👕",
    "categoryColor": "#C084FC",
    "keywords": [
      "одежда",
      "футболка",
      "джинсы",
      "куртка",
      "пальто",
      "рубашка",
      "свитер",
      "платье",
      "брюки",
      "носки",
      "белье",
      "zara",
      "uniqlo",
      "hm",
      "ostin",
      "befree",
      "lamoda",
      "wildberries одежда",
      "ozon одежда",
      "спортмастер одежда",
      "курточка"
    ]
  },
  {
    "id": "shoes",
    "type": "expense",
    "sectionId": "clothes",
    "sectionName": "Одежда",
    "sectionIcon": "👕",
    "sectionColor": "#C084FC",
    "categoryName": "Обувь",
    "categoryIcon": "👟",
    "categoryColor": "#C084FC",
    "keywords": [
      "обувь",
      "кроссовки",
      "ботинки",
      "сапоги",
      "туфли",
      "кеды",
      "сандали"
    ]
  },
  {
    "id": "accessories",
    "type": "expense",
    "sectionId": "clothes",
    "sectionName": "Одежда",
    "sectionIcon": "👕",
    "sectionColor": "#C084FC",
    "categoryName": "Аксессуары",
    "categoryIcon": "👜",
    "categoryColor": "#C084FC",
    "keywords": [
      "сумка",
      "рюкзак",
      "кошелек",
      "ремень",
      "часы",
      "очки",
      "аксессуары",
      "украшения",
      "цепочка",
      "кольцо"
    ]
  },
  {
    "id": "phone",
    "type": "expense",
    "sectionId": "electronics",
    "sectionName": "Техника",
    "sectionIcon": "📱",
    "sectionColor": "#60A5FA",
    "categoryName": "Телефон",
    "categoryIcon": "📱",
    "categoryColor": "#60A5FA",
    "keywords": [
      "телефон",
      "смартфон",
      "айфон",
      "iphone",
      "android",
      "чехол",
      "зарядка",
      "стекло",
      "powerbank",
      "пауэрбанк",
      "связной",
      "мвидео телефон",
      "dns телефон",
      "apple store",
      "app store",
      "ремонт телефона",
      "сим карта",
      "мобильник",
      "смартфон аксессуар"
    ]
  },
  {
    "id": "computer",
    "type": "expense",
    "sectionId": "electronics",
    "sectionName": "Техника",
    "sectionIcon": "📱",
    "sectionColor": "#60A5FA",
    "categoryName": "Компьютер",
    "categoryIcon": "💻",
    "categoryColor": "#60A5FA",
    "keywords": [
      "ноутбук",
      "компьютер",
      "пк",
      "монитор",
      "клавиатура",
      "мышка",
      "ssd",
      "процессор",
      "видеокарта",
      "планшет",
      "ipad"
    ]
  },
  {
    "id": "appliance",
    "type": "expense",
    "sectionId": "electronics",
    "sectionName": "Техника",
    "sectionIcon": "📱",
    "sectionColor": "#60A5FA",
    "categoryName": "Бытовая техника",
    "categoryIcon": "🔌",
    "categoryColor": "#60A5FA",
    "keywords": [
      "холодильник",
      "стиральная машина",
      "чайник",
      "микроволновка",
      "пылесос",
      "кофемашина",
      "духовка",
      "посудомойка"
    ]
  },
  {
    "id": "children",
    "type": "expense",
    "sectionId": "family",
    "sectionName": "Семья",
    "sectionIcon": "👨‍👩‍👧",
    "sectionColor": "#FBBF24",
    "categoryName": "Дети",
    "categoryIcon": "🧸",
    "categoryColor": "#FBBF24",
    "keywords": [
      "дети",
      "ребенок",
      "школа ребенку",
      "садик",
      "игрушки",
      "подгузники",
      "детское",
      "кружок",
      "детский",
      "детский мир",
      "акушерство",
      "школьная форма",
      "учеба ребенок",
      "садик оплата",
      "секция ребенку",
      "игрушка ребенку",
      "памперсы"
    ]
  },
  {
    "id": "parents",
    "type": "expense",
    "sectionId": "family",
    "sectionName": "Семья",
    "sectionIcon": "👨‍👩‍👧",
    "sectionColor": "#FBBF24",
    "categoryName": "Родители и семья",
    "categoryIcon": "👨‍👩‍👧",
    "categoryColor": "#FBBF24",
    "keywords": [
      "мама",
      "папа",
      "родители",
      "семья помощь",
      "родным",
      "бабушка",
      "дедушка"
    ]
  },
  {
    "id": "pets_food",
    "type": "expense",
    "sectionId": "pets",
    "sectionName": "Питомцы",
    "sectionIcon": "🐾",
    "sectionColor": "#A3E635",
    "categoryName": "Корм для питомца",
    "categoryIcon": "🐶",
    "categoryColor": "#A3E635",
    "keywords": [
      "корм",
      "кот",
      "кошка",
      "собака",
      "питомец",
      "животное",
      "наполнитель",
      "зоомагазин",
      "ветеринар",
      "ветклиника"
    ]
  }
];
