import type { TaxonomyIconRule } from '../types';

export const mobilityHomeRules: TaxonomyIconRule[] = [
  {
    "id": "taxi",
    "type": "expense",
    "sectionId": "transport",
    "sectionName": "Транспорт",
    "sectionIcon": "🚕",
    "sectionColor": "#60A5FA",
    "categoryName": "Такси",
    "categoryIcon": "🚕",
    "categoryColor": "#60A5FA",
    "keywords": [
      "такси",
      "яндекс такси",
      "uber",
      "убер",
      "bolt",
      "таксист",
      "поездка на такси",
      "ситимобил",
      "яндекс go",
      "таксопарк",
      "indrive",
      "gettaxi",
      "такси домой",
      "такси аэропорт",
      "поездка домой",
      "такси работа"
    ]
  },
  {
    "id": "public_transport",
    "type": "expense",
    "sectionId": "transport",
    "sectionName": "Транспорт",
    "sectionIcon": "🚕",
    "sectionColor": "#60A5FA",
    "categoryName": "Общественный транспорт",
    "categoryIcon": "🚌",
    "categoryColor": "#60A5FA",
    "keywords": [
      "автобус",
      "метро",
      "трамвай",
      "троллейбус",
      "маршрутка",
      "проезд",
      "транспортная карта",
      "подорожник",
      "тройка",
      "электричка",
      "метрополитен",
      "проездной",
      "единый билет",
      "карта тройка",
      "оплата проезда",
      "транспорт",
      "автобус билет",
      "маршрут"
    ]
  },
  {
    "id": "train",
    "type": "expense",
    "sectionId": "transport",
    "sectionName": "Транспорт",
    "sectionIcon": "🚕",
    "sectionColor": "#60A5FA",
    "categoryName": "Поезда",
    "categoryIcon": "🚆",
    "categoryColor": "#60A5FA",
    "keywords": [
      "поезд",
      "ржд",
      "сапсан",
      "ласточка",
      "купе",
      "плацкарт",
      "жд билет",
      "вокзал"
    ]
  },
  {
    "id": "fuel",
    "type": "expense",
    "sectionId": "auto",
    "sectionName": "Авто",
    "sectionIcon": "⛽",
    "sectionColor": "#FB7185",
    "categoryName": "Бензин",
    "categoryIcon": "⛽",
    "categoryColor": "#FB7185",
    "keywords": [
      "бензин",
      "топливо",
      "заправка",
      "азс",
      "дизель",
      "солярка",
      "газ",
      "gpn",
      "лукойл",
      "роснефть",
      "shell",
      "bp",
      "аи95",
      "аи92",
      "аи98",
      "заправился",
      "полный бак",
      "топливная карта",
      "газпромнефть",
      "татнефть",
      "бензоколонка"
    ]
  },
  {
    "id": "parking",
    "type": "expense",
    "sectionId": "auto",
    "sectionName": "Авто",
    "sectionIcon": "⛽",
    "sectionColor": "#FB7185",
    "categoryName": "Парковка",
    "categoryIcon": "🅿️",
    "categoryColor": "#FB7185",
    "keywords": [
      "парковка",
      "паркинг",
      "платная парковка",
      "штраф парковка",
      "стоянка"
    ]
  },
  {
    "id": "car_service",
    "type": "expense",
    "sectionId": "auto",
    "sectionName": "Авто",
    "sectionIcon": "⛽",
    "sectionColor": "#FB7185",
    "categoryName": "Обслуживание авто",
    "categoryIcon": "🔧",
    "categoryColor": "#FB7185",
    "keywords": [
      "сто",
      "сервис авто",
      "ремонт авто",
      "мойка",
      "шины",
      "резина",
      "масло",
      "техосмотр",
      "запчасти",
      "автосервис"
    ]
  },
  {
    "id": "car_insurance",
    "type": "expense",
    "sectionId": "auto",
    "sectionName": "Авто",
    "sectionIcon": "⛽",
    "sectionColor": "#FB7185",
    "categoryName": "Страховка авто",
    "categoryIcon": "🛡️",
    "categoryColor": "#FB7185",
    "keywords": [
      "осаго",
      "каско",
      "страховка авто",
      "автострахование"
    ]
  },
  {
    "id": "rent",
    "type": "expense",
    "sectionId": "home",
    "sectionName": "Дом",
    "sectionIcon": "🏠",
    "sectionColor": "#A78BFA",
    "categoryName": "Аренда",
    "categoryIcon": "🏘️",
    "categoryColor": "#A78BFA",
    "keywords": [
      "аренда",
      "квартира аренда",
      "съем жилья",
      "найм жилья",
      "снять квартиру",
      "жилье"
    ]
  },
  {
    "id": "mortgage",
    "type": "expense",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Ипотека",
    "categoryIcon": "🏦",
    "categoryColor": "#FCD34D",
    "keywords": [
      "ипотека",
      "ипотечный платеж",
      "кредит за квартиру",
      "жилищный кредит"
    ]
  },
  {
    "id": "repair",
    "type": "expense",
    "sectionId": "home",
    "sectionName": "Дом",
    "sectionIcon": "🏠",
    "sectionColor": "#A78BFA",
    "categoryName": "Ремонт",
    "categoryIcon": "🛠️",
    "categoryColor": "#A78BFA",
    "keywords": [
      "ремонт",
      "стройматериалы",
      "краска",
      "обои",
      "плитка",
      "ламинат",
      "инструменты",
      "двери",
      "сантехника",
      "мебель ремонт"
    ]
  },
  {
    "id": "furniture",
    "type": "expense",
    "sectionId": "home",
    "sectionName": "Дом",
    "sectionIcon": "🏠",
    "sectionColor": "#A78BFA",
    "categoryName": "Мебель",
    "categoryIcon": "🛋️",
    "categoryColor": "#A78BFA",
    "keywords": [
      "мебель",
      "диван",
      "кровать",
      "стол",
      "стул",
      "шкаф",
      "матрас",
      "тумба",
      "комод",
      "ikea",
      "икеа"
    ]
  },
  {
    "id": "household",
    "type": "expense",
    "sectionId": "home",
    "sectionName": "Дом",
    "sectionIcon": "🏠",
    "sectionColor": "#A78BFA",
    "categoryName": "Бытовые товары",
    "categoryIcon": "🧽",
    "categoryColor": "#A78BFA",
    "keywords": [
      "бытовая химия",
      "порошок",
      "моющее",
      "губки",
      "салфетки",
      "туалетная бумага",
      "хозтовары",
      "уборка",
      "перчатки"
    ]
  }
];
