import type { TaxonomyIconRule } from '../types';

export const paymentsRecurringRules: TaxonomyIconRule[] = [
  {
    "id": "electricity",
    "type": "expense",
    "sectionId": "utilities",
    "sectionName": "Коммунальные услуги",
    "sectionIcon": "💡",
    "sectionColor": "#38BDF8",
    "categoryName": "Электричество",
    "categoryIcon": "💡",
    "categoryColor": "#38BDF8",
    "keywords": [
      "электричество",
      "свет",
      "энергия",
      "электроэнергия",
      "мосэнергосбыт"
    ]
  },
  {
    "id": "water_bill",
    "type": "expense",
    "sectionId": "utilities",
    "sectionName": "Коммунальные услуги",
    "sectionIcon": "💡",
    "sectionColor": "#38BDF8",
    "categoryName": "Вода",
    "categoryIcon": "🚿",
    "categoryColor": "#38BDF8",
    "keywords": [
      "водоснабжение",
      "вода счет",
      "горячая вода",
      "холодная вода",
      "водоканал"
    ]
  },
  {
    "id": "gas_bill",
    "type": "expense",
    "sectionId": "utilities",
    "sectionName": "Коммунальные услуги",
    "sectionIcon": "💡",
    "sectionColor": "#38BDF8",
    "categoryName": "Газ",
    "categoryIcon": "🔥",
    "categoryColor": "#38BDF8",
    "keywords": [
      "газ коммуналка",
      "газоснабжение",
      "газпром межрегионгаз"
    ]
  },
  {
    "id": "internet",
    "type": "expense",
    "sectionId": "utilities",
    "sectionName": "Коммунальные услуги",
    "sectionIcon": "💡",
    "sectionColor": "#38BDF8",
    "categoryName": "Интернет",
    "categoryIcon": "🌐",
    "categoryColor": "#38BDF8",
    "keywords": [
      "интернет",
      "wi-fi",
      "вайфай",
      "провайдер",
      "домашний интернет",
      "роутер",
      "мгтс",
      "ростелеком"
    ]
  },
  {
    "id": "mobile",
    "type": "expense",
    "sectionId": "utilities",
    "sectionName": "Коммунальные услуги",
    "sectionIcon": "💡",
    "sectionColor": "#38BDF8",
    "categoryName": "Мобильная связь",
    "categoryIcon": "📶",
    "categoryColor": "#38BDF8",
    "keywords": [
      "телефон",
      "мобильная связь",
      "симка",
      "тариф",
      "сотовая связь",
      "мтс",
      "билайн",
      "мегафон",
      "tele2",
      "йота",
      "yota"
    ]
  },
  {
    "id": "streaming",
    "type": "expense",
    "sectionId": "subscriptions",
    "sectionName": "Подписки",
    "sectionIcon": "🔁",
    "sectionColor": "#818CF8",
    "categoryName": "Кино и музыка",
    "categoryIcon": "🎬",
    "categoryColor": "#818CF8",
    "keywords": [
      "netflix",
      "нетфликс",
      "ivi",
      "кинопоиск",
      "okko",
      "wink",
      "spotify",
      "яндекс музыка",
      "apple music",
      "youtube premium",
      "стриминг",
      "подписка кино",
      "музыка подписка",
      "amediateka",
      "more tv",
      "premier",
      "start",
      "твич",
      "twitch",
      "бусти",
      "boosty",
      "patreon",
      "telegram premium"
    ]
  },
  {
    "id": "software",
    "type": "expense",
    "sectionId": "subscriptions",
    "sectionName": "Подписки",
    "sectionIcon": "🔁",
    "sectionColor": "#818CF8",
    "categoryName": "Приложения и сервисы",
    "categoryIcon": "🧩",
    "categoryColor": "#818CF8",
    "keywords": [
      "подписка",
      "сервис",
      "приложение",
      "icloud",
      "google one",
      "notion",
      "figma",
      "adobe",
      "canva",
      "vpn",
      "антивирус",
      "openai",
      "chatgpt",
      "нейросеть",
      "github",
      "gitlab",
      "jetbrains",
      "cursor",
      "midjourney",
      "claude",
      "perplexity",
      "zoom",
      "slack",
      "microsoft 365",
      "office 365"
    ]
  },
  {
    "id": "games_sub",
    "type": "expense",
    "sectionId": "subscriptions",
    "sectionName": "Подписки",
    "sectionIcon": "🔁",
    "sectionColor": "#818CF8",
    "categoryName": "Игровые подписки",
    "categoryIcon": "🎮",
    "categoryColor": "#818CF8",
    "keywords": [
      "game pass",
      "ps plus",
      "playstation plus",
      "xbox",
      "steam подписка",
      "игровая подписка"
    ]
  }
];
