import type { TaxonomyIconRule } from '../types';

export const workIncomeExtraRules: TaxonomyIconRule[] = [
  {
    "id": "gift",
    "type": "expense",
    "sectionId": "gifts",
    "sectionName": "Подарки",
    "sectionIcon": "🎁",
    "sectionColor": "#FB7185",
    "categoryName": "Подарки",
    "categoryIcon": "🎁",
    "categoryColor": "#FB7185",
    "keywords": [
      "подарок",
      "подарки",
      "цветы",
      "сувенир",
      "день рождения",
      "праздник",
      "донат подарок"
    ]
  },
  {
    "id": "charity",
    "type": "expense",
    "sectionId": "gifts",
    "sectionName": "Подарки",
    "sectionIcon": "🎁",
    "sectionColor": "#FB7185",
    "categoryName": "Благотворительность",
    "categoryIcon": "🤝",
    "categoryColor": "#FB7185",
    "keywords": [
      "благотворительность",
      "донат",
      "пожертвование",
      "помощь",
      "сбор"
    ]
  },
  {
    "id": "office",
    "type": "expense",
    "sectionId": "work",
    "sectionName": "Работа",
    "sectionIcon": "💼",
    "sectionColor": "#94A3B8",
    "categoryName": "Офис и работа",
    "categoryIcon": "💼",
    "categoryColor": "#94A3B8",
    "keywords": [
      "офис",
      "канцелярия",
      "бумага",
      "ручки",
      "печать",
      "коворкинг",
      "рабочее место"
    ]
  },
  {
    "id": "business_expense",
    "type": "expense",
    "sectionId": "business",
    "sectionName": "Бизнес",
    "sectionIcon": "📊",
    "sectionColor": "#38BDF8",
    "categoryName": "Бизнес-расходы",
    "categoryIcon": "📊",
    "categoryColor": "#38BDF8",
    "keywords": [
      "бизнес расход",
      "закупка",
      "поставщик",
      "маркетинг",
      "реклама",
      "доставка клиенту",
      "командировка"
    ]
  },
  {
    "id": "salary",
    "type": "income",
    "sectionId": "income",
    "sectionName": "Доходы",
    "sectionIcon": "💰",
    "sectionColor": "#34D399",
    "categoryName": "Зарплата",
    "categoryIcon": "💰",
    "categoryColor": "#34D399",
    "keywords": [
      "зарплата",
      "аванс",
      "зп",
      "оклад",
      "получил зарплату",
      "премия",
      "работодатель",
      "перечисление зарплаты",
      "зарплатный проект",
      "получка",
      "месячная зарплата",
      "заработная плата"
    ]
  },
  {
    "id": "freelance",
    "type": "income",
    "sectionId": "income",
    "sectionName": "Доходы",
    "sectionIcon": "💰",
    "sectionColor": "#34D399",
    "categoryName": "Фриланс",
    "categoryIcon": "🧑‍💻",
    "categoryColor": "#34D399",
    "keywords": [
      "фриланс",
      "заказ",
      "клиент оплатил",
      "оплата проекта",
      "подработка",
      "гонорар",
      "фрилансер",
      "upwork",
      "kwork",
      "freelancehunt",
      "заказчик",
      "проект оплатили",
      "оплата работы",
      "работа на стороне"
    ]
  },
  {
    "id": "business_income",
    "type": "income",
    "sectionId": "business",
    "sectionName": "Бизнес",
    "sectionIcon": "📊",
    "sectionColor": "#38BDF8",
    "categoryName": "Бизнес-доход",
    "categoryIcon": "📈",
    "categoryColor": "#38BDF8",
    "keywords": [
      "выручка",
      "продажа",
      "оплата клиента",
      "доход бизнеса",
      "поступление от клиента",
      "касса"
    ]
  },
  {
    "id": "cashback",
    "type": "income",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Кэшбэк",
    "categoryIcon": "💸",
    "categoryColor": "#FCD34D",
    "keywords": [
      "кэшбек",
      "cashback",
      "бонусы",
      "проценты на остаток",
      "возврат бонусов",
      "тинькофф кэшбек",
      "тбанк кэшбек",
      "альфа бонус",
      "сберспасибо",
      "бонусная программа",
      "мили",
      "баллы"
    ]
  },
  {
    "id": "refund",
    "type": "income",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Возврат",
    "categoryIcon": "↩️",
    "categoryColor": "#FCD34D",
    "keywords": [
      "возврат",
      "вернули деньги",
      "refund",
      "компенсация",
      "возмещение"
    ]
  },
  {
    "id": "gift_income",
    "type": "income",
    "sectionId": "gifts",
    "sectionName": "Подарки",
    "sectionIcon": "🎁",
    "sectionColor": "#FB7185",
    "categoryName": "Подаренные деньги",
    "categoryIcon": "🎁",
    "categoryColor": "#FB7185",
    "keywords": [
      "подарили деньги",
      "подарок деньгами",
      "перевели подарок",
      "денежный подарок"
    ]
  },
  {
    "id": "investment_income",
    "type": "income",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Инвестиции",
    "categoryIcon": "📈",
    "categoryColor": "#FCD34D",
    "keywords": [
      "дивиденды",
      "купон",
      "инвестиции доход",
      "прибыль акции",
      "проценты вклад",
      "вклад"
    ]
  },
  {
    "id": "rental_income",
    "type": "income",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Арендный доход",
    "categoryIcon": "🏘️",
    "categoryColor": "#FCD34D",
    "keywords": [
      "аренда доход",
      "сдал квартиру",
      "арендатор заплатил",
      "доход от аренды"
    ]
  },
  {
    "id": "extra_0",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Продукты",
    "categoryIcon": "🛒",
    "categoryColor": "#34D399",
    "keywords": [
      "пятерочка",
      "перекресток",
      "магнит",
      "лента",
      "ашан",
      "вкусвилл",
      "самокат",
      "лавка",
      "окей",
      "metro",
      "глобус",
      "дикси",
      "верный",
      "монетка",
      "ярче",
      "spar",
      "азбука вкуса",
      "delivery club продукты",
      "sbermarket",
      "купил продукты",
      "продуктовый магазин",
      "еда домой"
    ]
  },
  {
    "id": "extra_1",
    "type": "expense",
    "sectionId": "electronics",
    "sectionName": "Техника",
    "sectionIcon": "📱",
    "sectionColor": "#60A5FA",
    "categoryName": "Техника и электроника",
    "categoryIcon": "📱",
    "categoryColor": "#60A5FA",
    "keywords": [
      "dns",
      "мвидео",
      "эльдорадо",
      "ситилинк",
      "re store",
      "apple",
      "xiaomi",
      "samsung",
      "huawei",
      "honor",
      "техника",
      "электроника",
      "гаджет",
      "наушники",
      "airpods",
      "колонка",
      "телевизор",
      "камера",
      "принтер",
      "сканер"
    ]
  },
  {
    "id": "extra_2",
    "type": "expense",
    "sectionId": "home",
    "sectionName": "Дом",
    "sectionIcon": "🏠",
    "sectionColor": "#A78BFA",
    "categoryName": "Дом и быт",
    "categoryIcon": "🏠",
    "categoryColor": "#A78BFA",
    "keywords": [
      "леруа",
      "obi",
      "петрович",
      "hoff",
      "home market",
      "посуда",
      "тарелки",
      "сковорода",
      "кастрюля",
      "ножи",
      "подушка",
      "одеяло",
      "плед",
      "шторы",
      "лампа",
      "светильник",
      "ковер",
      "декор"
    ]
  },
  {
    "id": "extra_3",
    "type": "expense",
    "sectionId": "beauty",
    "sectionName": "Красота",
    "sectionIcon": "💅",
    "sectionColor": "#F472B6",
    "categoryName": "Красота и уход",
    "categoryIcon": "💅",
    "categoryColor": "#F472B6",
    "keywords": [
      "летуаль",
      "рив гош",
      "золотое яблоко",
      "подружка",
      "магнит косметик",
      "уход за лицом",
      "уход за телом",
      "спа",
      "массаж",
      "брови",
      "ресницы",
      "косметолог",
      "эпиляция"
    ]
  },
  {
    "id": "extra_4",
    "type": "expense",
    "sectionId": "travel",
    "sectionName": "Путешествия",
    "sectionIcon": "✈️",
    "sectionColor": "#2DD4BF",
    "categoryName": "Путешествия",
    "categoryIcon": "✈️",
    "categoryColor": "#2DD4BF",
    "keywords": [
      "booking",
      "ostrovok",
      "aviasales",
      "tutu",
      "яндекс путешествия",
      "суточно",
      "trip",
      "билеты самолет",
      "билеты поезд",
      "отпуск расходы",
      "чемодан",
      "багаж",
      "трансфер",
      "экскурсии"
    ]
  },
  {
    "id": "extra_5",
    "type": "expense",
    "sectionId": "finance",
    "sectionName": "Финансы",
    "sectionIcon": "🏦",
    "sectionColor": "#FCD34D",
    "categoryName": "Финансы",
    "categoryIcon": "🏦",
    "categoryColor": "#FCD34D",
    "keywords": [
      "сбер",
      "тинькофф",
      "тбанк",
      "альфа банк",
      "втб",
      "озон банк",
      "райффайзен",
      "газпромбанк",
      "банк",
      "перевод себе",
      "комиссия банка",
      "обслуживание",
      "проценты",
      "страховка"
    ]
  }
];
