import type { TaxonomyIconRule } from '../types';

export const extraRules: TaxonomyIconRule[] = [
  {
      "id": "extra_0",
      "type": "expense",
      "sectionId": "groceries",
      "sectionName": "Продуктовый магазин",
      "sectionIcon": "🛒",
      "sectionColor": "#34D399",
      "categoryName": "Продукты",
      "categoryIcon": "🛒",
      "categoryColor": "#34D399",
      "keywords": [
        "пятерочка",
        "перекресток",
        "магнит",
        "лента",
        "ашан",
        "вкусвилл",
        "самокат",
        "лавка",
        "окей",
        "metro",
        "глобус",
        "дикси",
        "верный",
        "монетка",
        "ярче",
        "spar",
        "азбука вкуса",
        "delivery club продукты",
        "sbermarket",
        "купил продукты",
        "продуктовый магазин",
        "еда домой"
      ]
    },
  {
      "id": "extra_1",
      "type": "expense",
      "sectionId": "electronics",
      "sectionName": "Техника",
      "sectionIcon": "📱",
      "sectionColor": "#60A5FA",
      "categoryName": "Техника и электроника",
      "categoryIcon": "📱",
      "categoryColor": "#60A5FA",
      "keywords": [
        "dns",
        "мвидео",
        "эльдорадо",
        "ситилинк",
        "re store",
        "apple",
        "xiaomi",
        "samsung",
        "huawei",
        "honor",
        "техника",
        "электроника",
        "гаджет",
        "наушники",
        "airpods",
        "колонка",
        "телевизор",
        "камера",
        "принтер",
        "сканер"
      ]
    },
  {
      "id": "extra_2",
      "type": "expense",
      "sectionId": "home",
      "sectionName": "Дом",
      "sectionIcon": "🏠",
      "sectionColor": "#A78BFA",
      "categoryName": "Дом и быт",
      "categoryIcon": "🏠",
      "categoryColor": "#A78BFA",
      "keywords": [
        "леруа",
        "obi",
        "петрович",
        "hoff",
        "home market",
        "посуда",
        "тарелки",
        "сковорода",
        "кастрюля",
        "ножи",
        "подушка",
        "одеяло",
        "плед",
        "шторы",
        "лампа",
        "светильник",
        "ковер",
        "декор"
      ]
    },
  {
      "id": "extra_3",
      "type": "expense",
      "sectionId": "beauty",
      "sectionName": "Красота",
      "sectionIcon": "💅",
      "sectionColor": "#F472B6",
      "categoryName": "Красота и уход",
      "categoryIcon": "💅",
      "categoryColor": "#F472B6",
      "keywords": [
        "летуаль",
        "рив гош",
        "золотое яблоко",
        "подружка",
        "магнит косметик",
        "уход за лицом",
        "уход за телом",
        "спа",
        "массаж",
        "брови",
        "ресницы",
        "косметолог",
        "эпиляция"
      ]
    },
  {
      "id": "extra_4",
      "type": "expense",
      "sectionId": "travel",
      "sectionName": "Путешествия",
      "sectionIcon": "✈️",
      "sectionColor": "#2DD4BF",
      "categoryName": "Путешествия",
      "categoryIcon": "✈️",
      "categoryColor": "#2DD4BF",
      "keywords": [
        "booking",
        "ostrovok",
        "aviasales",
        "tutu",
        "яндекс путешествия",
        "суточно",
        "trip",
        "билеты самолет",
        "билеты поезд",
        "отпуск расходы",
        "чемодан",
        "багаж",
        "трансфер",
        "экскурсии"
      ]
    },
  {
      "id": "extra_5",
      "type": "expense",
      "sectionId": "finance",
      "sectionName": "Финансы",
      "sectionIcon": "🏦",
      "sectionColor": "#FCD34D",
      "categoryName": "Финансы",
      "categoryIcon": "🏦",
      "categoryColor": "#FCD34D",
      "keywords": [
        "сбер",
        "тинькофф",
        "тбанк",
        "альфа банк",
        "втб",
        "озон банк",
        "райффайзен",
        "газпромбанк",
        "банк",
        "перевод себе",
        "комиссия банка",
        "обслуживание",
        "проценты",
        "страховка"
      ]
    }
];
