import type { TaxonomyIconRule } from '../types';

export const foodRules: TaxonomyIconRule[] = [
  {
    "id": "sausage",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Мясо и колбасы",
    "categoryIcon": "🌭",
    "categoryColor": "#34D399",
    "keywords": [
      "колбаса",
      "сосиски",
      "сардельки",
      "ветчина",
      "бекон",
      "салями",
      "мясо",
      "говядина",
      "свинина",
      "курица",
      "индейка",
      "фарш",
      "котлеты",
      "стейк",
      "карбонат",
      "грудинка",
      "докторская",
      "сервелат",
      "купаты",
      "шашлык",
      "куриное филе",
      "окорочка",
      "бедро куриное",
      "мясной магазин",
      "мясницкий ряд",
      "колбасный",
      "пельмени мясо"
    ]
  },
  {
    "id": "dairy",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Молочные продукты",
    "categoryIcon": "🥛",
    "categoryColor": "#34D399",
    "keywords": [
      "молоко",
      "кефир",
      "йогурт",
      "сыр",
      "творог",
      "сметана",
      "сливки",
      "масло сливочное",
      "ряженка",
      "айран",
      "моцарелла",
      "пармезан",
      "активиа",
      "данон",
      "простоквашино",
      "домик в деревне",
      "сырок",
      "творожок",
      "биойогурт",
      "маскарпоне",
      "брынза",
      "адыгейский сыр",
      "молочка"
    ]
  },
  {
    "id": "bakery",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Хлеб и выпечка",
    "categoryIcon": "🥖",
    "categoryColor": "#34D399",
    "keywords": [
      "хлеб",
      "батон",
      "булка",
      "булочка",
      "лаваш",
      "круассан",
      "пирожок",
      "выпечка",
      "багет",
      "лепешка",
      "пита",
      "пекарня",
      "хлебозавод",
      "буханка",
      "сдоба",
      "баранки",
      "сушки",
      "пирог",
      "пироги",
      "ватрушка",
      "слойка",
      "булочная"
    ]
  },
  {
    "id": "vegetables",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Овощи",
    "categoryIcon": "🥦",
    "categoryColor": "#34D399",
    "keywords": [
      "овощи",
      "помидоры",
      "огурцы",
      "картошка",
      "картофель",
      "морковь",
      "лук",
      "капуста",
      "перец",
      "баклажан",
      "кабачок",
      "зелень",
      "салат",
      "свекла",
      "чеснок",
      "овощной",
      "огурчик",
      "томат",
      "черри",
      "авокадо",
      "шпинат",
      "руккола",
      "петрушка",
      "укроп",
      "кинза",
      "сельдерей",
      "редис"
    ]
  },
  {
    "id": "fruits",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Фрукты",
    "categoryIcon": "🍎",
    "categoryColor": "#34D399",
    "keywords": [
      "фрукты",
      "яблоки",
      "бананы",
      "апельсины",
      "мандарины",
      "груши",
      "виноград",
      "манго",
      "киви",
      "лимон",
      "арбуз",
      "дыня",
      "персики",
      "ягоды",
      "клубника",
      "малина",
      "фруктовый",
      "голубика",
      "ежевика",
      "смородина",
      "ананас",
      "гранат",
      "слива",
      "абрикос",
      "нектарин",
      "черешня",
      "вишня"
    ]
  },
  {
    "id": "fish",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Рыба и морепродукты",
    "categoryIcon": "🐟",
    "categoryColor": "#34D399",
    "keywords": [
      "рыба",
      "лосось",
      "семга",
      "тунец",
      "форель",
      "селедка",
      "креветки",
      "мидии",
      "кальмар",
      "икра",
      "морепродукты",
      "суши набор",
      "рыбный",
      "сельдь",
      "скумбрия",
      "минтай",
      "треска",
      "краб",
      "крабовые палочки",
      "осьминог",
      "устрицы",
      "морской коктейль"
    ]
  },
  {
    "id": "sweets",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Сладости",
    "categoryIcon": "🍫",
    "categoryColor": "#34D399",
    "keywords": [
      "шоколад",
      "конфеты",
      "печенье",
      "торт",
      "пирожное",
      "вафли",
      "мармелад",
      "сладости",
      "мороженое",
      "чипсы сладкие",
      "батончик",
      "десерт"
    ]
  },
  {
    "id": "snacks",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Снеки",
    "categoryIcon": "🍿",
    "categoryColor": "#34D399",
    "keywords": [
      "чипсы",
      "сухарики",
      "орешки",
      "попкорн",
      "снэки",
      "снеки",
      "крекер",
      "фисташки",
      "арахис",
      "семечки"
    ]
  },
  {
    "id": "water",
    "type": "expense",
    "sectionId": "groceries",
    "sectionName": "Продукты",
    "sectionIcon": "🛒",
    "sectionColor": "#34D399",
    "categoryName": "Вода и напитки",
    "categoryIcon": "🥤",
    "categoryColor": "#34D399",
    "keywords": [
      "вода",
      "газировка",
      "сок",
      "лимонад",
      "кола",
      "напиток",
      "энергетик",
      "чай бутылка",
      "минералка",
      "морс",
      "компот"
    ]
  },
  {
    "id": "coffee",
    "type": "expense",
    "sectionId": "food",
    "sectionName": "Еда вне дома",
    "sectionIcon": "🍽️",
    "sectionColor": "#F59E0B",
    "categoryName": "Кофе",
    "categoryIcon": "☕",
    "categoryColor": "#F59E0B",
    "keywords": [
      "кофе",
      "латте",
      "капучино",
      "американо",
      "эспрессо",
      "раф",
      "кофейня",
      "старбакс",
      "старбак",
      "кофеек",
      "флэт уайт",
      "кофе с собой",
      "кофикс",
      "cofix",
      "кофепорт",
      "кофемания",
      "шоколадница кофе",
      "кофейный",
      "кофе хауз",
      "дубльби",
      "surf coffee",
      "one price coffee"
    ]
  },
  {
    "id": "cafe",
    "type": "expense",
    "sectionId": "food",
    "sectionName": "Еда вне дома",
    "sectionIcon": "🍽️",
    "sectionColor": "#F59E0B",
    "categoryName": "Кафе и рестораны",
    "categoryIcon": "🍽️",
    "categoryColor": "#F59E0B",
    "keywords": [
      "кафе",
      "ресторан",
      "обед",
      "ужин",
      "завтрак",
      "столовая",
      "фастфуд",
      "бургер",
      "пицца",
      "шаурма",
      "роллы",
      "суши",
      "доставка еды",
      "макдональдс",
      "вкусно и точка",
      "kfc",
      "бургер кинг",
      "додо",
      "доминос",
      "теремок",
      "бургер",
      "мак",
      "ростикс",
      "вкусвилл кафе",
      "рест",
      "кафешка",
      "ланч",
      "бизнес ланч",
      "еда доставка"
    ]
  },
  {
    "id": "bar",
    "type": "expense",
    "sectionId": "food",
    "sectionName": "Еда вне дома",
    "sectionIcon": "🍽️",
    "sectionColor": "#F59E0B",
    "categoryName": "Бары",
    "categoryIcon": "🍸",
    "categoryColor": "#F59E0B",
    "keywords": [
      "бар",
      "коктейль",
      "паб",
      "лаунж",
      "кальян",
      "вечеринка",
      "настойка",
      "сидр",
      "безалкогольный бар"
    ]
  }
];
