import { AIToolDefinition } from './tool-types';

export const AI_TOOL_REGISTRY: AIToolDefinition[] = [
  {
    name: 'create_account',
    description: 'Create account/wallet/card/cash/savings/investment. Use with initialBalance when user says to create account and put/add money there.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { name: 'string', type: 'cash|card|savings|investment|null', currency: 'RUB|USD|EUR|VND|null', initialBalance: 'number|string|null' },
  },
  {
    name: 'update_account',
    description: 'Change account fields.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { account: 'string', name: 'string|null', type: 'cash|card|savings|investment|null', currency: 'RUB|USD|EUR|VND|null', balance: 'number|string|null' },
  },
  {
    name: 'delete_account',
    description: 'Delete account. Dangerous.',
    risk: 'high',
    requiresConfirmation: true,
    input: { account: 'string' },
  },
  {
    name: 'delete_accounts',
    description: 'Delete multiple accounts or all accounts. Use only when user explicitly asks to delete all/several accounts. Dangerous and always requires confirmation.',
    risk: 'high',
    requiresConfirmation: true,
    input: { accounts: 'string[]|null', scope: 'all|selected' },
  },
  {
    name: 'set_primary_account',
    description: 'Set default/primary account for expenses and/or income. Use when user says make account primary/main/default.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { account: 'string', scope: 'expense|income|both|null' },
  },
  {
    name: 'create_transaction',
    description: 'Record expense/income/top-up/deposit/salary. Backend validates amount, balance and auto-execute policy.',
    risk: 'low',
    requiresConfirmation: false,
    input: { kind: 'income|expense', amount: 'number|string', currency: 'RUB|USD|EUR|VND|null', account: 'string|null', category: 'string|null', section: 'string|null', description: 'string|null' },
  },
  {
    name: 'transfer_money',
    description: 'Move money between two accounts.',
    risk: 'high',
    requiresConfirmation: true,
    input: { fromAccount: 'string', toAccount: 'string', amount: 'number|string', currency: 'RUB|USD|EUR|VND|null', description: 'string|null' },
  },
  {
    name: 'create_category',
    description: 'Create category.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { name: 'string', type: 'income|expense', section: 'string|null' },
  },
  {
    name: 'create_section',
    description: 'Create section for grouping categories/transactions.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { name: 'string' },
  },
  {
    name: 'create_goal',
    description: 'Create financial goal/savings target. Use for goals like laptop, travel, emergency fund, moving.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { title: 'string', targetAmount: 'number|string', currentAmount: 'number|string|null', currency: 'RUB|USD|EUR|VND|null', account: 'string|null', note: 'string|null' },
  },
  {
    name: 'update_goal',
    description: 'Update existing financial goal: title, target amount, current amount, status, note.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { goal: 'string', title: 'string|null', targetAmount: 'number|string|null', currentAmount: 'number|string|null', status: 'active|completed|archived|null', note: 'string|null' },
  },
  {
    name: 'delete_goal',
    description: 'Delete/archive a financial goal. Dangerous.',
    risk: 'high',
    requiresConfirmation: true,
    input: { goal: 'string' },
  },
  {
    name: 'show_goals',
    description: 'Show financial goals.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'show_accounts',
    description: 'Show accounts.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'show_transactions',
    description: 'Show recent transactions.',
    risk: 'low',
    requiresConfirmation: false,
    input: { limit: 'number|null' },
  },
  {
    name: 'show_ai_settings',
    description: 'Show AI/user automation settings, default accounts, onboarding state and presets.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'update_ai_settings',
    description: 'Update AI settings: default accounts, auto-confirm limits, companion tone.',
    risk: 'medium',
    requiresConfirmation: true,
    input: {
      defaultExpenseAccount: 'string|null',
      defaultIncomeAccount: 'string|null',
      autoConfirmExpenseLimit: 'number|string|null',
      autoConfirmIncomeLimit: 'number|string|null',
      autoConfirmTransferLimit: 'number|string|null',
      requireConfirmForAccountActions: 'boolean|null',
      companionTone: 'calm|friendly|strict|coach|null',
    },
  },
  {
    name: 'apply_ai_settings_preset',
    description: 'Apply recommended AI settings preset: strict, balanced or simple.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { preset: 'strict|balanced|simple' },
  },
  {
    name: 'update_onboarding_state',
    description: 'Update interactive onboarding/tutorial state.',
    risk: 'low',
    requiresConfirmation: false,
    input: { status: 'not_started|active|completed|null', currentStep: 'string|null', skipped: 'boolean|null' },
  },
  {
    name: 'restart_onboarding',
    description: 'Restart optional interactive onboarding/tutorial.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'query_analytics',
    description: 'Answer analytics questions about spending, income, balance, categories, accounts and periods.',
    risk: 'low',
    requiresConfirmation: false,
    input: { period: 'today|week|month|year|all|null', metric: 'summary|spending|income|top_categories|accounts|cashflow|null', limit: 'number|null' },
  },
  {
    name: 'undo_last_action',
    description: 'Undo/revert the latest AI-created financial transaction when safe.',
    risk: 'high',
    requiresConfirmation: true,
    input: { target: 'last|transaction|null' },
  },
  {
    name: 'show_companion_reactions',
    description: 'Show recent AI companion reaction events/signals.',
    risk: 'low',
    requiresConfirmation: false,
    input: { limit: 'number|null', onlyUnseen: 'boolean|null' },
  },
  {
    name: 'mark_companion_reactions_seen',
    description: 'Mark AI companion reactions as seen.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'show_premium_capabilities',
    description: 'Show premium-ready capability boundaries and enabled flags.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
];

export function getToolDefinition(name: string) {
  return AI_TOOL_REGISTRY.find((tool) => tool.name === name);
}

export function getPlannerToolContract() {
  return [
    'create_transaction{kind:income|expense,amount,account,category,section,description,currency} // account/category/section are natural names, never ids',
    'create_account{name,type:cash|card|savings|investment,currency,initialBalance} // initialBalance 0 when money is added by transaction',
    'update_account{account,name,type,currency,balance} // rename/change existing account; account is current account name',
    'delete_account{account} // delete one account by name',
    'delete_accounts{scope:all|selected,accounts} // delete all or selected accounts only when user explicitly asks',
    'set_primary_account{account,scope:expense|income|both} // primary/default/main account',
    'transfer_money{fromAccount,toAccount,amount,currency,description}',
    'create_goal{title,targetAmount,currentAmount,currency,account,note}',
    'update_goal{goal,title,targetAmount,currentAmount,status,note}',
    'delete_goal{goal}',
    'show_goals{}',
    'show_accounts{}',
    'show_transactions{limit}',
    'query_analytics{period,metric,limit}',
    'undo_last_action{target}',
    'show_companion_reactions{limit,onlyUnseen}',
    'mark_companion_reactions_seen{}',
    'show_premium_capabilities{}',
    'show_ai_settings{}',
    'update_ai_settings{defaultExpenseAccount,defaultIncomeAccount,autoConfirmExpenseLimit,autoConfirmIncomeLimit,autoConfirmTransferLimit,requireConfirmForAccountActions,companionTone}',
    'apply_ai_settings_preset{preset:strict|balanced|simple}',
    'update_onboarding_state{status,currentStep,skipped}',
    'restart_onboarding{}',
  ].join('\n');
}

