import { AIToolDefinition } from './tool-types';

export const AI_TOOL_REGISTRY: AIToolDefinition[] = [
  {
    name: 'create_account',
    description: 'Create account/wallet/card/cash/savings/investment. Use with initialBalance when user says to create account and put/add money there.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { name: 'string', type: 'cash|card|savings|investment|null', currency: 'RUB|USD|EUR|VND|null', initialBalance: 'number|string|null' },
  },
  {
    name: 'update_account',
    description: 'Change account fields.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { account: 'string', name: 'string|null', type: 'cash|card|savings|investment|null', currency: 'RUB|USD|EUR|VND|null', balance: 'number|string|null' },
  },
  {
    name: 'delete_account',
    description: 'Delete account. Dangerous.',
    risk: 'high',
    requiresConfirmation: true,
    input: { account: 'string' },
  },
  {
    name: 'delete_accounts',
    description: 'Delete multiple accounts or all accounts. Use only when user explicitly asks to delete all/several accounts. Dangerous and always requires confirmation.',
    risk: 'high',
    requiresConfirmation: true,
    input: { accounts: 'string[]|null', scope: 'all|selected' },
  },
  {
    name: 'set_primary_account',
    description: 'Set default/primary account for expenses and/or income. Use when user says make account primary/main/default.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { account: 'string', scope: 'expense|income|both|null' },
  },
  {
    name: 'create_transaction',
    description: 'Record one finished expense or income. Use semantic fields: category = broad money purpose, merchant/place = where it happened, items/tags/description = context. Do not use this for transfers, goals, obligations, or recurring payments. Do not use section for new user transactions.',
    risk: 'low',
    requiresConfirmation: false,
    input: { kind: 'income|expense', amount: 'number|string', currency: 'RUB|USD|EUR|VND|null', account: 'string|null', title: 'short clean label|null', category: 'broad financial meaning|null', section: 'legacy|null', description: 'notes/context|null', merchant: 'store/person/company|null', place: 'location/channel|null', items: 'purchased item meanings[]|null', tags: 'search context[]|null' },
  },
  {
    name: 'update_transaction',
    description: 'Edit an existing income/expense/transfer operation. Use for corrections to amount, title, description, account, category, type or date. Never use create_transaction when the user asks to change, fix, correct, rename or edit an existing operation.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { transaction: 'string|null', target: 'last|last_income|last_expense|last_transfer|null', kind: 'income|expense|transfer|null', amount: 'number|string|null', currency: 'RUB|USD|EUR|VND|null', account: 'string|null', toAccount: 'string|null', category: 'string|null', section: 'string|null', description: 'string|null', date: 'string|null' },
  },
  {
    name: 'transfer_money',
    description: 'Move money between two accounts.',
    risk: 'high',
    requiresConfirmation: true,
    input: { fromAccount: 'string', toAccount: 'string', amount: 'number|string', currency: 'RUB|USD|EUR|VND|null', description: 'string|null' },
  },
  {
    name: 'create_category',
    description: 'Create a broad transaction category. Do not create sections.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { name: 'string', type: 'income|expense', section: 'legacy|null' },
  },
  {
    name: 'update_category',
    description: 'Rename or change category type. Ignore sections.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { category: 'string', name: 'string|null', type: 'income|expense|null', section: 'legacy|null' },
  },
  {
    name: 'delete_category',
    description: 'Delete category. Existing transactions keep amount and lose category link.',
    risk: 'high',
    requiresConfirmation: true,
    input: { category: 'string' },
  },
  {
    name: 'create_section',
    description: 'Legacy hidden section command. Do not use for user-facing taxonomy; create broad categories instead.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { name: 'string' },
  },
  {
    name: 'update_section',
    description: 'Legacy hidden section command. Do not use for user-facing taxonomy.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { section: 'string', name: 'string' },
  },
  {
    name: 'delete_section',
    description: 'Delete section. Categories and transactions keep data and lose section link.',
    risk: 'high',
    requiresConfirmation: true,
    input: { section: 'string' },
  },
  {
    name: 'assign_category_to_section',
    description: 'Legacy hidden section command. Do not use; categories are single-layer now.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { category: 'string', section: 'string' },
  },
  {
    name: 'show_taxonomy',
    description: 'Show categories.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'create_goal',
    description: 'Create financial goal/savings target. Goal creation is never an expense and never income: the amount is targetAmount. If no account is provided, backend creates a linked savings account for the goal. Use autoSavePercent when the user wants to save a percent from every income, for example 10 percent to emergency fund.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { title: 'string', targetAmount: 'number|string', currentAmount: 'number|string|null', currency: 'RUB|USD|EUR|VND|null', account: 'string|null', autoSavePercent: 'number|string|null', note: 'string|null' },
  },
  {
    name: 'update_goal',
    description: 'Update existing financial goal: title, target amount, current amount, status, note.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { goal: 'string', title: 'string|null', targetAmount: 'number|string|null', currentAmount: 'number|string|null', autoSavePercent: 'number|string|null', status: 'active|completed|archived|null', note: 'string|null' },
  },
  {
    name: 'delete_goal',
    description: 'Delete/archive a financial goal. Dangerous.',
    risk: 'high',
    requiresConfirmation: true,
    input: { goal: 'string' },
  },
  {
    name: 'show_goals',
    description: 'Show financial goals.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'show_accounts',
    description: 'Show accounts.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'show_transactions',
    description: 'Show recent transactions.',
    risk: 'low',
    requiresConfirmation: false,
    input: { limit: 'number|null' },
  },
  {
    name: 'show_ai_settings',
    description: 'Show AI/user automation settings, default accounts, onboarding state and presets.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'update_ai_settings',
    description: 'Update AI settings: default accounts, auto-confirm limits, companion tone.',
    risk: 'medium',
    requiresConfirmation: true,
    input: {
      defaultExpenseAccount: 'string|null',
      defaultIncomeAccount: 'string|null',
      autoConfirmExpenseLimit: 'number|string|null',
      autoConfirmIncomeLimit: 'number|string|null',
      autoConfirmTransferLimit: 'number|string|null',
      requireConfirmForAccountActions: 'boolean|null',
      companionTone: 'calm|friendly|strict|coach|null',
    },
  },
  {
    name: 'apply_ai_settings_preset',
    description: 'Apply recommended AI settings preset: strict, balanced or simple.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { preset: 'strict|balanced|simple' },
  },
  {
    name: 'update_onboarding_state',
    description: 'Update interactive onboarding/tutorial state.',
    risk: 'low',
    requiresConfirmation: false,
    input: { status: 'not_started|active|completed|null', currentStep: 'string|null', skipped: 'boolean|null' },
  },
  {
    name: 'restart_onboarding',
    description: 'Restart optional interactive onboarding/tutorial.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
  {
    name: 'query_analytics',
    description: 'Answer analytics questions about spending, income, balance, categories, accounts, periods and filtered transaction searches. Use filter/search/category when the user asks for expenses about a specific place, category, item or word such as cafe, taxi or medicine.',
    risk: 'low',
    requiresConfirmation: false,
    input: { period: 'today|week|month|year|all|null', metric: 'summary|spending|income|top_categories|accounts|cashflow|null', limit: 'number|null', filter: 'specific place/category/item/search text|null', category: 'category name|null', search: 'search text|null' },
  },
  {
    name: 'undo_last_action',
    description: 'Undo/revert the latest AI-created financial transaction when safe.',
    risk: 'high',
    requiresConfirmation: true,
    input: { target: 'last|transaction|null' },
  },
  {
    name: 'show_companion_reactions',
    description: 'Show recent AI companion reaction events/signals.',
    risk: 'low',
    requiresConfirmation: false,
    input: { limit: 'number|null', onlyUnseen: 'boolean|null' },
  },
  {
    name: 'mark_companion_reactions_seen',
    description: 'Mark AI companion reactions as seen.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },

  {
    name: 'create_obligation',
    description: 'Create a loan, mortgage, installment, subscription or other recurring obligation with payment reminder. Use when user says they have a credit/loan/mortgage/installment/subscription or wants to add an obligatory payment. This is not a normal expense.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { title: 'string', type: 'loan|mortgage|installment|subscription|other|null', creditor: 'string|null', principalAmount: 'number|string|null', currentDebt: 'number|string|null', monthlyPayment: 'number|string|null', currency: 'RUB|USD|EUR|VND|null', interestRate: 'number|string|null', termMonths: 'number|string|null', paidMonths: 'number|string|null', paymentDay: 'number|string|null', nextPaymentDate: 'string|null', reminderDaysBefore: 'number|string|null', account: 'string|null', autoCreateExpense: 'boolean|null', note: 'string|null' },
  },
  {
    name: 'update_obligation',
    description: 'Edit an existing loan/mortgage/installment/subscription/obligation: payment amount, debt, payment day, reminder, write-off account, status or note.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { obligation: 'string', title: 'string|null', type: 'loan|mortgage|installment|subscription|other|null', creditor: 'string|null', principalAmount: 'number|string|null', currentDebt: 'number|string|null', monthlyPayment: 'number|string|null', currency: 'RUB|USD|EUR|VND|null', interestRate: 'number|string|null', termMonths: 'number|string|null', paidMonths: 'number|string|null', paymentDay: 'number|string|null', nextPaymentDate: 'string|null', reminderDaysBefore: 'number|string|null', account: 'string|null', autoCreateExpense: 'boolean|null', status: 'active|paused|closed|null', note: 'string|null' },
  },
  {
    name: 'delete_obligation',
    description: 'Delete an obligation/loan/mortgage/installment/subscription. Dangerous and requires confirmation.',
    risk: 'high',
    requiresConfirmation: true,
    input: { obligation: 'string' },
  },
  {
    name: 'mark_obligation_paid',
    description: 'Mark obligation payment as paid. Optionally create an expense from selected account if user asks to write off/spend from account or obligation has autoCreateExpense enabled.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { obligation: 'string', amount: 'number|string|null', account: 'string|null', paidAt: 'string|null', createExpense: 'boolean|null', note: 'string|null' },
  },
  {
    name: 'show_obligations',
    description: 'Show obligations, loans, mortgages, installments, subscriptions, reminders and upcoming required payments.',
    risk: 'low',
    requiresConfirmation: false,
    input: { status: 'active|paused|closed|all|null' },
  },
  {
    name: 'create_obligation_reminder',
    description: 'Create a custom reminder connected to an obligation or standalone required payment reminder.',
    risk: 'medium',
    requiresConfirmation: true,
    input: { obligation: 'string|null', title: 'string', message: 'string|null', dueDate: 'string|null', remindAt: 'string|null', channel: 'app|bot|both|null' },
  },

  {
    name: 'create_spending_limit',
    description: 'Create a spending limit for an account, expense category, or total expenses. Use for commands like set a monthly limit on card, limit cafes to 10000, control total spending.',
    risk: 'medium',
    requiresConfirmation: false,
    input: { targetType: 'account|category|total', account: 'string|null', category: 'string|null', amount: 'number|string', period: 'daily|weekly|monthly|null', notifyAt: 'number|string|null' },
  },
  {
    name: 'update_spending_limit',
    description: 'Change an existing spending limit amount, period, target, or active state.',
    risk: 'medium',
    requiresConfirmation: false,
    input: { limit: 'string|null', targetType: 'account|category|total|null', account: 'string|null', category: 'string|null', amount: 'number|string|null', period: 'daily|weekly|monthly|null', notifyAt: 'number|string|null', isActive: 'boolean|null' },
  },
  {
    name: 'delete_spending_limit',
    description: 'Delete a spending limit. Use only when user explicitly asks to delete/remove a limit.',
    risk: 'high',
    requiresConfirmation: true,
    input: { limit: 'string|null', targetType: 'account|category|total|null', account: 'string|null', category: 'string|null' },
  },
  {
    name: 'show_spending_limits',
    description: 'Show spending limits, budget limits and progress.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },

  {
    name: 'show_premium_capabilities',
    description: 'Show premium-ready capability boundaries and enabled flags.',
    risk: 'low',
    requiresConfirmation: false,
    input: {},
  },
];

export function getToolDefinition(name: string) {
  return AI_TOOL_REGISTRY.find((tool) => tool.name === name);
}

export function getPlannerToolContract() {
  return [
    'create_transaction{kind:income|expense,amount,account,title,category,description,merchant,place,items,tags,currency} // account/category are natural names, never ids; category is the broad meaning; merchant/place/items/tags describe context',
    'update_transaction{transaction,target:last|last_income|last_expense|last_transfer,kind,amount,account,toAccount,category,description,date,currency} // edit existing operation; use for corrections, never create a duplicate',
    'create_account{name,type:cash|card|savings|investment,currency,initialBalance} // initialBalance 0 when money is added by transaction',
    'update_account{account,name,type,currency,balance} // rename/change existing account; account is current account name',
    'delete_account{account} // delete one account by name',
    'delete_accounts{scope:all|selected,accounts} // delete all or selected accounts only when user explicitly asks',
    'set_primary_account{account,scope:expense|income|both} // primary/default/main account',
    'transfer_money{fromAccount,toAccount,amount,currency,description}',
    'create_category{name,type:income|expense} // create one broad category; do not create sections',
    'update_category{category,name,type} // rename/change one broad category; do not use sections',
    'delete_category{category}',
    'show_taxonomy{}',
    'create_goal{title,targetAmount,currentAmount,currency,account,note}',
    'update_goal{goal,title,targetAmount,currentAmount,status,note}',
    'delete_goal{goal}',
    'show_goals{}',
    'create_obligation{title,type,creditor,principalAmount,currentDebt,monthlyPayment,currency,interestRate,termMonths,paidMonths,paymentDay,nextPaymentDate,reminderDaysBefore,account,autoCreateExpense,note}',
    'update_obligation{obligation,title,type,creditor,principalAmount,currentDebt,monthlyPayment,currency,interestRate,termMonths,paidMonths,paymentDay,nextPaymentDate,reminderDaysBefore,account,autoCreateExpense,status,note}',
    'delete_obligation{obligation}',
    'mark_obligation_paid{obligation,amount,account,paidAt,createExpense,note}',
    'show_obligations{status}',
    'create_obligation_reminder{obligation,title,message,dueDate,remindAt,channel}',
    'show_accounts{}',
    'show_transactions{limit}',
    'query_analytics{period,metric,limit,filter,category,search}',
    'undo_last_action{target}',
    'show_companion_reactions{limit,onlyUnseen}',
    'mark_companion_reactions_seen{}',
    'show_premium_capabilities{}',
    'show_ai_settings{}',
    'update_ai_settings{defaultExpenseAccount,defaultIncomeAccount,autoConfirmExpenseLimit,autoConfirmIncomeLimit,autoConfirmTransferLimit,requireConfirmForAccountActions,companionTone}',
    'apply_ai_settings_preset{preset:strict|balanced|simple}',
    'update_onboarding_state{status,currentStep,skipped}',
    'restart_onboarding{}',
  ].join('\n');
}

